CREATE TABLE FILES (
    ID NUMBER,
    CONSTRAINT FILE_ID PRIMARY KEY (id),
    NAME NVARCHAR2 (30),
    FORMAT NVARCHAR2 (30),
    SIZING NUMBER,
    STORAGE_ID NUMBER,
    CONSTRAINT FILE_FK FOREIGN KEY (STORAGE_ID) REFERENCES STORAGE (ID)
);